import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white'>
      <header className='bg-white pt-24 px-4 flex text-gray text-4xl md:text-6xl h-24 items-center justify-center font-bold'>
        crossbuilders challenge
      </header>
      {children}</body>
    </html>
  )
}
